Buildspec.yml:
version: 0.2

phases:
  pre_build:
    commands:
      # Authenticate Docker with ECR
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      # Pull the Docker Hub image
      - echo "Pulling image from Docker Hub..."
      - docker pull osmanjem/travelinspirationapp:latest

  build:
    commands:
      # Tag the image for ECR
      - echo "Tagging image..."
      - docker tag osmanjem/travelinspirationapp:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      # Push the image to ECR
      - echo "Pushing image to ECR..."
      - docker push $REPOSITORY_URI:latest
      # Generate imagedefinitions.json for ECS deployment
      - echo "Generating imagedefinitions.json..."
      - printf '[{"name":"travelinspiration-container","imageUri":"%s"}]' "$REPOSITORY_URI:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json 